### ISSUE TITLE
Unable to upload to mediawiki: illegal-filename and NullPointerException

### ISSUE THREAD

**Issue by urieli** [fastily/jwiki#35]
**jwiki version:** 1.8.0

Mediawiki versions:
Product | Version
-- | --
MediaWiki | 1.36.1
PHP | 7.4.21 (apache2handler)
MariaDB | 10.6.3-MariaDB-1:10.6.3+maria~focal
ICU | 63.1

I'm trying to get upload to work, but it's failing with a NullPointerException due to a JSON "illegal-filename" error.

Here is my test code:
```java
import okhttp3.HttpUrl;
import org.fastily.jwiki.core.Wiki;

import java.nio.file.Path;

public class WikiTest {
  public static void main(String[] args) throws Exception {
    HttpUrl mediawikiUrl = HttpUrl.parse("http://localhost:8087/api.php");

    Wiki wiki = new Wiki.Builder()
        .withApiEndpoint(mediawikiUrl)
        .withLogin("wikiuser", "*********")
        .build();

    System.out.println(wiki.getPageText("Main Page") );
    
    Path testFile = Path.of("test");

    wiki.upload(testFile, "File:test", "test description", "test reason");
  }
}
```

The file `test` is at the root and contains the word "test".

Here is the output:
```
Aug 06, 2021 05:06:28 PM
INFO: [<Anonymous> @ localhost]: Try login for wikiuser
Aug 06, 2021 05:06:29 PM
INFO: [Wikiuser @ localhost]: Getting user rights for Wikiuser
Aug 06, 2021 05:06:29 PM
INFO: [Wikiuser @ localhost]: Logged in as wikiuser
Aug 06, 2021 05:06:29 PM
INFO: [Wikiuser @ localhost]: Fetching Namespace List
Aug 06, 2021 05:06:29 PM
INFO: [Wikiuser @ localhost]: Getting page text of Main Page
<strong>MediaWiki has been installed.</strong>

Consult the [https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents User's Guide] for information on using the wiki software.

== Getting started ==
* [https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:Configuration_settings Configuration settings list]
* [https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:FAQ MediaWiki FAQ]
* [https://lists.wikimedia.org/mailman/listinfo/mediawiki-announce MediaWiki release mailing list]
* [https://www.mediawiki.org/wiki/Special:MyLanguage/Localisation#Translation_resources Localise MediaWiki for your language]
* [https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:Combating_spam Learn how to combat spam on your wiki]
* [[Test page]]
Aug 06, 2021 05:06:29 PM
INFO: [Wikiuser @ localhost]: Uploading test
Aug 06, 2021 05:06:29 PM
FYI: [Wikiuser @ localhost]: Uploading chunk [1 of 1] of 'test'
Aug 06, 2021 05:06:29 PM
ERROR: [Wikiuser @ localhost]: Encountered an error, retrying - 0
java.lang.NullPointerException
	at org.fastily.jwiki.util.GSONP.getStr(GSONP.java:189)
	at org.fastily.jwiki.core.WAction.upload(WAction.java:223)
	at org.fastily.jwiki.core.Wiki.upload(Wiki.java:611)
	at com.joliciel.cnes.kiwi.WikiTest.main(WikiTest.java:30)
Aug 06, 2021 05:06:29 PM
ERROR: [Wikiuser @ localhost]: Encountered an error, retrying - 1
java.lang.NullPointerException
	at org.fastily.jwiki.util.GSONP.getStr(GSONP.java:189)
	at org.fastily.jwiki.core.WAction.upload(WAction.java:223)
	at org.fastily.jwiki.core.Wiki.upload(Wiki.java:611)
	at com.joliciel.cnes.kiwi.WikiTest.main(WikiTest.java:30)
Aug 06, 2021 05:06:29 PM
ERROR: [Wikiuser @ localhost]: Encountered an error, retrying - 2
java.lang.NullPointerException
	at org.fastily.jwiki.util.GSONP.getStr(GSONP.java:189)
	at org.fastily.jwiki.core.WAction.upload(WAction.java:223)
	at org.fastily.jwiki.core.Wiki.upload(Wiki.java:611)
	at com.joliciel.cnes.kiwi.WikiTest.main(WikiTest.java:30)
Aug 06, 2021 05:06:29 PM
ERROR: [Wikiuser @ localhost]: Encountered an error, retrying - 3
java.lang.NullPointerException
	at org.fastily.jwiki.util.GSONP.getStr(GSONP.java:189)
	at org.fastily.jwiki.core.WAction.upload(WAction.java:223)
	at org.fastily.jwiki.core.Wiki.upload(Wiki.java:611)
	at com.joliciel.cnes.kiwi.WikiTest.main(WikiTest.java:30)
Aug 06, 2021 05:06:29 PM
ERROR: [Wikiuser @ localhost]: Encountered an error, retrying - 4
java.lang.NullPointerException
	at org.fastily.jwiki.util.GSONP.getStr(GSONP.java:189)
	at org.fastily.jwiki.core.WAction.upload(WAction.java:223)
	at org.fastily.jwiki.core.Wiki.upload(Wiki.java:611)
	at com.joliciel.cnes.kiwi.WikiTest.main(WikiTest.java:30)
Aug 06, 2021 05:06:29 PM
INFO: [Wikiuser @ localhost]: Unstashing 'null' as 'File:test'
Aug 06, 2021 05:06:29 PM
ERROR: [Wikiuser @ localhost]: Encountered an error while unstashing, retrying - 0
Aug 06, 2021 05:06:29 PM
INFO: [Wikiuser @ localhost]: Unstashing 'null' as 'File:test'
Aug 06, 2021 05:06:29 PM
ERROR: [Wikiuser @ localhost]: Encountered an error while unstashing, retrying - 1
Aug 06, 2021 05:06:29 PM
INFO: [Wikiuser @ localhost]: Unstashing 'null' as 'File:test'
Aug 06, 2021 05:06:29 PM
ERROR: [Wikiuser @ localhost]: Encountered an error while unstashing, retrying - 2

Process finished with exit code 0
```
As you can see, the login and retrieve page work, but the upload fails.

When I place a breakpoint at gson-2.8.6.jar/com.google.gson line 47:
```java
public static JsonElement parseString(String json) throws JsonSyntaxException {
    return parseReader(new StringReader(json));
  }
```
I see the following JSON:
```json
{
  "error": {
    "code": "illegal-filename",
    "info": "The filename is not allowed.",
    "*": "See http://localhost:8087/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes."
  }
}
```

The `NullPointException` seems to be caused by the `illegal-filename` error. However, I cannot find anyway of discovering what is illegal about the filename "File:test".

I also tried with the filename "test" (although the class says to prefix with "File:"), but the identical error occurs.

First: the `NullPointerException` should instead return a meaningful exception.

Second: the input seems valid, why is mediawiki returning an "illegal-filename" exception? It would seem jwiki is doing something wrong.

**Comment by fastily** [comment]
HI @urieli.  You'll need to specify a file extension.  For example, if `test` is a txt file, then you need to add a `.txt` extension like so:

```java
wiki.upload(testFile, "File:Test.txt", "test description", "test reason");
```

**Comment by urieli** [comment]
@fastily I get the identical error with 
```java
wiki.upload(testFile, "File:Test.txt", "test description", "test reason");
```
Also the identical error if I rename the file itself from "test" to "test.txt".

**Comment by fastily** [comment]
Can you please try uploading an image file (e.g. jpg, png)?

**Comment by urieli** [comment]
With a ".jpg" it worked. 

The call was:
```java
    Path testFile = Path.of("test.jpg");
    wiki.upload(testFile, "File:test.jpg", "test description", "test reason");
```

The question is, how to get it to work for uploading of new wiki pages. Maybe I need a file in a particular format.

I tried with the following XML file, which uploads correctly if I go to http://localhost:8087/index.php/Special:Import

But via the API it gives me the identical error:
```java
    Path testFile = Path.of("test.xml");
    wiki.upload(testFile, "File:test.xml", "test description", "test reason");
```

Contents of `test.xml`:
```xml
<mediawiki xmlns="http://www.mediawiki.org/xml/export-0.10/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mediawiki.org/xml/export-0.10/ http://www.mediawiki.org/xml/export-0.10.xsd" version="0.10" xml:lang="fr">
  <page>
    <title>test</title>
    <ns>0</ns>
    <id>1</id>
    <revision>
      <id>1</id>
      <comment>Automatically generated</comment>
      <model>wikitext</model>
      <format>text/x-wiki</format>
      <text xml:space="preserve">testing 1 2 3</text>
    </revision>
  </page>
</mediawiki>
```

**Comment by fastily** [comment]
housekeeping, closed per above
