### ISSUE TITLE
resolveRedirect cause NPE

### ISSUE THREAD

**Issue by primael** [fastily/jwiki#7]
When I call resolveRedirect I've a NullPointerException
`java.lang.NullPointerException: null
	at java.util.ArrayList.addAll(ArrayList.java:581)
	at fastily.jwiki.core.MQuery.getNoContList(MQuery.java:127)
	at fastily.jwiki.core.MQuery.resolveRedirects(MQuery.java:418)
	at fastily.jwiki.core.Wiki.resolveRedirect(Wiki.java:1030)`

To reproduce:

`
String titre = "Java EE";
Wiki wiki = new Wiki("fr.wikipedia.org");
String redirection = wiki.resolveRedirect(titre);;
`

**Comment by fastily** [comment]
Hi @primael, thanks for the bug report!  I'll investigate.
