### ISSUE TITLE
Login problems

### ISSUE THREAD

**Issue by xbony2** [fastily/jwiki#8]
I'm probably just doing this wrong, but doing...
```groovy
wiki = new Wiki(args[1], args[2], "ftb.gamepedia.com")
```
gives me...
```
INFO: [32m[<Anonymous> @ ftb.gamepedia.com]: Try login for ESAEBSAD@ESAEBSAD-bot[0m
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at fastily.jwiki.core.WQuery.next(WQuery.java:297)
	at fastily.jwiki.core.Wiki.getTokens(Wiki.java:218)
	at fastily.jwiki.core.Wiki.login(Wiki.java:179)
	at fastily.jwiki.core.Wiki.<init>(Wiki.java:86)
	at fastily.jwiki.core.Wiki.<init>(Wiki.java:106)
	at fastily.jwiki.core.Wiki.<init>(Wiki.java:145)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at xbony2.esaebsad2.ESAEBSAD2.main(ESAEBSAD2.groovy:37)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
	... 17 more
java.lang.NullPointerException
	at fastily.jwiki.core.Wiki.getTokens(Wiki.java:218)
	at fastily.jwiki.core.Wiki.login(Wiki.java:179)
	at fastily.jwiki.core.Wiki.<init>(Wiki.java:86)
	at fastily.jwiki.core.Wiki.<init>(Wiki.java:106)
	at fastily.jwiki.core.Wiki.<init>(Wiki.java:145)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at xbony2.esaebsad2.ESAEBSAD2.main(ESAEBSAD2.groovy:37)
Exception in thread "main" java.lang.SecurityException: Failed to log-in as null @ ftb.gamepedia.com
	at fastily.jwiki.core.Wiki.<init>(Wiki.java:87)
	at fastily.jwiki.core.Wiki.<init>(Wiki.java:106)
	at fastily.jwiki.core.Wiki.<init>(Wiki.java:145)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at xbony2.esaebsad2.ESAEBSAD2.main(ESAEBSAD2.groovy:37)
```
The arguments should be right ("ESAEBSAD@ESAEBSAD-bot" and my password).

**Comment by fastily** [comment]
Hi @xbony2 , I'm unable to reproduce this in my environment.  Could you post the output from jwiki's debug mode?  The code to run would look something like this:

```java
Wiki wiki = new Wiki("ftb.gamepedia.com");
wiki.conf.debug = true;
wiki.login(args[1], args[2]);
```

**Comment by xbony2** [comment]
Full thing:
```
Working Directory: /Users/xbony2/git/ESAEBSAD2
Gradle User Home: /Users/xbony2/.gradle
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 4.3
Java Home: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home
JVM Arguments: None
Program Arguments: None
Build Scans Enabled: false
Offline Mode Enabled: false
Gradle Tasks: run

:compileJava NO-SOURCE
:compileGroovy
:processResources NO-SOURCE
:classes
:runSLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
[main] INFO JDA - Login Successful!
[JDA MainWS-ReadThread] INFO WebSocketClient - Connected to WebSocket
[JDA MainWS-ReadThread] INFO JDA - Finished Loading!
May 19, 2018 09:25:11 AM
INFO: [32m[<Anonymous> @ ftb.gamepedia.com]: Fetching Namespace List[0m
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at fastily.jwiki.core.WQuery.next(WQuery.java:297)
	at fastily.jwiki.core.Wiki.<init>(Wiki.java:91)
	at fastily.jwiki.core.Wiki.<init>(Wiki.java:106)
	at fastily.jwiki.core.Wiki.<init>(Wiki.java:145)
	at fastily.jwiki.core.Wiki.<init>(Wiki.java:155)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at xbony2.esaebsad2.ESAEBSAD2.main(ESAEBSAD2.groovy:34)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
	... 16 more
Exception in thread "main" java.lang.NullPointerException
	at fastily.jwiki.core.Wiki.<init>(Wiki.java:91)
	at fastily.jwiki.core.Wiki.<init>(Wiki.java:106)
	at fastily.jwiki.core.Wiki.<init>(Wiki.java:145)
	at fastily.jwiki.core.Wiki.<init>(Wiki.java:155)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at xbony2.esaebsad2.ESAEBSAD2.main(ESAEBSAD2.groovy:34)
```

using
```groovy
wiki = new Wiki("ftb.gamepedia.com") //line 34
wiki.conf.debug = true
wiki.login(args[1], args[2])
```

Am I missing anything?

**Comment by xbony2** [comment]
It seems to be working now ^^
